name: RuneCraft
version: '1.0-SNAPSHOT'
main: hoffmantv.runeCraft.RuneCraft
api-version: '1.21'
authors: [ HoffmanTV ]
description: Brining all the best of RuneScape to Minecraft
commands:
  setfishingspot:
    description: Set a fishing spot at your current location.
    usage: /setfishingspot
    permission: rc.fishingspotset
  clearinv:
    description: Clears your inventory.
    usage: /clearinv
    permission: rc.clearinventory
  skills:
    description: Displays your skill information.
    usage: /skills
  setmobspawn:
    description: Spawns a mob at a specific location.
    usage: /setmobspawn
    permission: rc.mobspawnset
  scoreboard:
    description: Toggle the skills scoreboard on and off.
    usage: /scoreboard
  generatecourse:
    description: Generates an agility course in front of the player.
    usage: /generatecourse
    permission: rc.generatecourse
  agility:
    description: Agility skill commands.
    usage: /agility <start|gen|level>
    permission: rc.agility